name: Starter Kit Extension Build and Deploy Package

on: [push]

env:
  AZURE_ARTIFACTS_FEED_URL: https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Enable longpaths
        run: |
          git version
          git config --global core.longpaths true

      - name: Checkout Ed-Fi-ODS
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
          path: Ed-Fi-ODS/
          ref: v6.0

      - name: Checkout Ed-Fi-ODS-Implementation
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation
          path: Ed-Fi-ODS-Implementation/
          ref: v6.0

      - name: Checkout Starter Kit Sample Extension
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
        with:
          repository: Ed-Fi-Alliance-OSS/Starter-Kit-SEA-Modernization
          path: Starter-Kit-SEA-Modernization/

      - name: Initialize-DevelopmentEnvironment
        shell: powershell
        run: |
          & $env:GITHUB_WORKSPACE/Starter-Kit-SEA-Modernization/.github/workflows/build.ps1
