name: Starter Kit Extension Build and Deploy Package

on: [push]

env:
  AZURE_ARTIFACTS_FEED_URL: https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json

jobs:
  build-and-test:
    runs-on: windows-latest
    container:
      runs-on: windows-latest
      container: edfialliance/mssql-server-windows-express
      
    steps:
      - name: Enable longpaths
        run: |
          git version
          git config --global core.longpaths true

      - name: Checkout Ed-Fi-ODS
        uses: actions/checkout@v2.3.4
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
          path: Ed-Fi-ODS/
          ref: main

      - name: Checkout Ed-Fi-ODS-Implementation
        uses: actions/checkout@v2.3.4
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation
          path: Ed-Fi-ODS-Implementation/
          ref: ODS-5089-localdb


      - name: Checkout Starter Kit Sample Extension
        uses: actions/checkout@v2.3.4
        with:
          repository: Ed-Fi-Alliance-OSS/Starter-Kit-SEA-Modernization
          path: Starter-Kit-SEA-Modernization/

      - name: Setup .NET Core SDK 3.1.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: "3.1.x"
          source-url: ${{ env.AZURE_ARTIFACTS_FEED_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}

      - name: Initialize-DevelopmentEnvironment
        shell: powershell
        run: |
          & $env:GITHUB_WORKSPACE/Starter-Kit-SEA-Modernization/.github/workflows/build.ps1
